In [13]:
import torch

In [14]:
x = torch.arange(4.0)

x.requires_grad_(True)

x.grad

x


tensor([0., 1., 2., 3.], requires_grad=True)

In [15]:
y = 2 * torch.dot(x, x)

y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()

x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad